FROM fabiocicerchia/nginx-lua

RUN apk add --no-cache vim curl lsof certbot certbot-nginx build-base 
RUN luarocks install lua-resty-jwt 
RUN luarocks install lua-cjson

COPY init.conf /etc/nginx/nginx.conf

CMD ["nginx", "-g", "daemon off;"]
