apiVersion: apps/v1
kind: Deployment
metadata:
    name: openresty
spec:
    replicas: 1
    selector:
        matchLabels:
            app: openresty
    template:
        metadata:
            labels:
                app: openresty
        spec:
            containers:
                - name: openresty
                  image: 2land/openresty:da2_v0
                  ports:
                      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: openresty-service
spec:
    selector:
        app: openresty
    ports:
        - protocol: TCP
          port: 80 # Cổng service expose
          targetPort: 80 # Cổng trong container ứng dụng
    type: LoadBalancer
